### ISSUE TITLE
Detections computing error

### ISSUE THREAD

**Issue by kaoutharzohra** [crossminer/maracas#78]
Hello,

**Context** :  After running successfully the command mavenReport for delta computing, I tried the command 
 mavenReport(|file:///Users/path/to/output/folder|, "javax.servlet", "javax.servlet-api", "3.0.1", "3.1.0", cgroup="org.springframework", cartifact="spring-test", cv="4.2.5.RELEASE") for getting the impact detection on the client.
**Result** : callfailed error : 
![Screenshot from 2023-02-22 12-10-52](https://user-images.githubusercontent.com/17832152/220616364-c2b66941-74ea-484b-b0d6-1189c77e8b63.jpeg)

**Goal**:  to run successfully the command and to show the detections list in the generated report.
Thank you

**Comment by tdegueul** [comment]
Hi @kaoutharzohra,

Thanks for getting in touch. Unfortunately, this repository is no longer maintained and Maracas has moved to its new home at [alien-tools/maracas](https://github.com/alien-tools/maracas). We forgot to redirect to the new repository in our README, which I just fixed thanks to you, sorry about that.

Maracas has been rewritten entirely as a plain Java library and does not rely on Rascal anymore, which should greatly simplify its use on your side. If you still have a chance to move to the new Maracas, I strongly suggest you give it a try and we'll be there to help you if necessary.

If you'd like to stick with this very old Maracas version, let me know and I'll have a look by myself as it would need deeper investigation.

**Comment by kaoutharzohra** [comment]
Thank you so much, I can get the set of impacts using the new maracas !
I printed the set  "brokenUses"  and I tried to check the output in the code, does "brokenUses" represent the broken uses leading to compilation errors in the client or just the impacted parts used in non-breaking way or both?

Thanks again :)

**Comment by tdegueul** [comment]
Awesome, you were fast! The `brokenUses` represent the elements in client code that are impacted by a breaking change in the library (and won't compile if the client upgrades). Bear in mind that Maracas must sometimes over-estimate the impact of some breaking changes due to missing information (this is particularly the case with BCs related to super-types such as `INTERFACE_ADDED`, `SUPERCLASS_REMOVED`, etc).

I close the issue on this side but don't hesitate to open a new one on the new repository if you have any questions. We'll be happy to help.

Cheers,
